name: Deploy
 
on: [push]
 
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
        BACK: ${{ secrets.BACK }}
        FRONT: ${{ secrets.FRONT }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: BACK,FRONT
        script: |
          bash $BACK/client/run.sh
          bash $FRONT/client/run.sh
